DjangoMarket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path("",include('core.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path("admin/", admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# 加上static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 讓在開發環境時，可以透過指定的 url 訪問在 media/item_images 下的圖片
# 例如 : http://localhost:8000/media/item_images/hq720.jpg

conversation/urls.py
from django.urls import path

from . import views


app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name='core'

urlpatterns=[
      path('',views.index,name='index'),
      path('contact/',views.contact,name='contact'),
      path('signup/',views.signup,name='signup'),
      path('login/',auth_views.LoginView.as_view(authentication_form=LoginForm,template_name='core/login.html'),name='login')
]

item/urls.py
from django.urls import path

from . import views

app_name='item'

urlpatterns = [
    path('',views.items,name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=260)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = '種類分類'

    def __str__(self):
        return self.name 


class Items(models.Model):
    name = models.CharField(max_length=260)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    # 告訴 Django 要將圖片放在哪一個資料夾
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)  
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name 

    class Meta:
        verbose_name_plural = '項目'



#ForeignKey(Category, related_name='items', on_delete=models.CASCADE):
#這表示Items模型中的category字段是一個外鍵，指向Category模型。這表示每個Items實例都會關聯到一個Category實例。

#related_name='items':
# 這個屬性設置了從Category實例反向查找關聯Items的名稱。也就是說，如果你有一個Category實例，你可以使用category.items.all()來獲取所有屬於該分類的Items。

# on_delete=models.CASCADE:
# 這表示當關聯的Category實例被刪除時，所有關聯的Items實例也會被自動刪除。

# 如以下的範例

# Category:

# 名稱：電子產品 (id=1)
# 名稱：家具 (id=2)
# Items:

# 名稱：筆記本電腦，分類：電子產品
# 名稱：手機，分類：電子產品
# 名稱：沙發，分類：家具
# python
# 複製程式碼
# # 首先，創建Category實例
# category_electronics = Category.objects.create(name='電子產品')
# category_furniture = Category.objects.create(name='家具')

# # 創建Items實例並關聯到對應的Category
# item_laptop = Items.objects.create(name='筆記本電腦', category=category_electronics, price=1000.0, created_by=user)
# item_phone = Items.objects.create(name='手機', category=category_electronics, price=800.0, created_by=user)
# item_sofa = Items.objects.create(name='沙發', category=category_furniture, price=500.0, created_by=user)

# # 使用category實例的related_name屬性來查詢所有關聯的Items
# electronics_items = category_electronics.items.all()
# furniture_items = category_furniture.items.all()

item/forms.py
from django import forms

from .models import Items

INPUT_CLASS='w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
      class Meta:
            model=Items
            fields=('category','name','description','image','price',)

            widgets={
                  'category': forms.Select(attrs={
                        'class':INPUT_CLASS
                  }),
                  'name': forms.TextInput(attrs={
                        'class':INPUT_CLASS
                  }),
                   'description': forms.Textarea(attrs={
                        'class':INPUT_CLASS
                  }),
                  'price': forms.TextInput(attrs={
                        'class':INPUT_CLASS
                  }),
                  'image': forms.FileInput(attrs={
                        'class':INPUT_CLASS
                  }),
            }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Items
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASS
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASS
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASS
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASS
            })
        }

item/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from .models import Items,Category
from django.db.models import Q
from .forms import NewItemForm,EditItemForm


def items(request):
    query=request.GET.get('query','')
    items=Items.objects.filter(is_sold=False)
    category_id=request.GET.get('category',0)
    categories=Category.objects.all()

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    if category_id:
        items = items.filter(category_id=category_id)


    return render(request,'item/items.html',{
        'items':items,
        'query':query,
        'categories':categories,
        'category_id':int(category_id)
    })

def details(request, pk):
    item = get_object_or_404(Items, pk=pk)
    # 將尚未出售且排除當前商品的前三項給抓出來
    related_items = Items.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Items, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:details', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Items, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>
    
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}

        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your item!</p>

                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}  
            <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:details' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
      <div class="col-span-1">
            <form method="get" action="{% url 'item:items' %}">
                  <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">
  
                  <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
              </form>
              
              <hr class="my-6">

              <p class="font-semibold">Categories</p>
  
              <ul>
                  {% for category in categories %}
                      <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                          <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                      </li>
                  {% endfor %}
              </ul>
              <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>

      </div>
      <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                  {% for item in items %}
                    <div>
                        <a href="{% url 'item:details' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
      </div>
</div>


{% endblock %}